// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: currency_rate.proto

// Vendored from currency-rate-service (github.com/DigitLock/currency-rate-service),
// proto/currency_rate/v1/service.proto. Contract is owned by that service; this is a
// client-side copy for ET's gRPC client. Keep the proto package as currency_rate.v1
// so the service full name matches the CRS server. Only go_package is repointed to
// ET's pb output. Re-sync on CRS contract changes (see docs/discovery/v0.3.0-st1-discovery.md).

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency   string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency     string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Rate           float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsOutdated     bool                   `protobuf:"varint,5,opt,name=is_outdated,json=isOutdated,proto3" json:"is_outdated,omitempty"`
	SourceProvider string                 `protobuf:"bytes,6,opt,name=source_provider,json=sourceProvider,proto3" json:"source_provider,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_currency_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{0}
}

func (x *Rate) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *Rate) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *Rate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Rate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Rate) GetIsOutdated() bool {
	if x != nil {
		return x.IsOutdated
	}
	return false
}

func (x *Rate) GetSourceProvider() string {
	if x != nil {
		return x.SourceProvider
	}
	return ""
}

type CurrencyPair struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency           string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency             string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	PollingIntervalSeconds int32                  `protobuf:"varint,3,opt,name=polling_interval_seconds,json=pollingIntervalSeconds,proto3" json:"polling_interval_seconds,omitempty"`
	IsActive               bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CurrencyPair) Reset() {
	*x = CurrencyPair{}
	mi := &file_currency_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyPair) ProtoMessage() {}

func (x *CurrencyPair) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyPair.ProtoReflect.Descriptor instead.
func (*CurrencyPair) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyPair) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CurrencyPair) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CurrencyPair) GetPollingIntervalSeconds() int32 {
	if x != nil {
		return x.PollingIntervalSeconds
	}
	return 0
}

func (x *CurrencyPair) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_currency_rate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{2}
}

func (x *GetRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type GetRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *Rate                  `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	mi := &file_currency_rate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{3}
}

func (x *GetRateResponse) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type GetRatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency     string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	TargetCurrencies []string               `protobuf:"bytes,2,rep,name=target_currencies,json=targetCurrencies,proto3" json:"target_currencies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_currency_rate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{4}
}

func (x *GetRatesRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetRatesRequest) GetTargetCurrencies() []string {
	if x != nil {
		return x.TargetCurrencies
	}
	return nil
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*Rate                `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_currency_rate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{5}
}

func (x *GetRatesResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type ListSupportedPairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedPairsRequest) Reset() {
	*x = ListSupportedPairsRequest{}
	mi := &file_currency_rate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedPairsRequest) ProtoMessage() {}

func (x *ListSupportedPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedPairsRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedPairsRequest) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{6}
}

type ListSupportedPairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*CurrencyPair        `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedPairsResponse) Reset() {
	*x = ListSupportedPairsResponse{}
	mi := &file_currency_rate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedPairsResponse) ProtoMessage() {}

func (x *ListSupportedPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_rate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedPairsResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedPairsResponse) Descriptor() ([]byte, []int) {
	return file_currency_rate_proto_rawDescGZIP(), []int{7}
}

func (x *ListSupportedPairsResponse) GetPairs() []*CurrencyPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_currency_rate_proto protoreflect.FileDescriptor

const file_currency_rate_proto_rawDesc = "" +
	"\n" +
	"\x13currency_rate.proto\x12\x10currency_rate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\x04Rate\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vis_outdated\x18\x05 \x01(\bR\n" +
	"isOutdated\x12'\n" +
	"\x0fsource_provider\x18\x06 \x01(\tR\x0esourceProvider\"\xab\x01\n" +
	"\fCurrencyPair\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x128\n" +
	"\x18polling_interval_seconds\x18\x03 \x01(\x05R\x16pollingIntervalSeconds\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"V\n" +
	"\x0eGetRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"=\n" +
	"\x0fGetRateResponse\x12*\n" +
	"\x04rate\x18\x01 \x01(\v2\x16.currency_rate.v1.RateR\x04rate\"c\n" +
	"\x0fGetRatesRequest\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\x12+\n" +
	"\x11target_currencies\x18\x02 \x03(\tR\x10targetCurrencies\"@\n" +
	"\x10GetRatesResponse\x12,\n" +
	"\x05rates\x18\x01 \x03(\v2\x16.currency_rate.v1.RateR\x05rates\"\x1b\n" +
	"\x19ListSupportedPairsRequest\"R\n" +
	"\x1aListSupportedPairsResponse\x124\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1e.currency_rate.v1.CurrencyPairR\x05pairs2\xa9\x02\n" +
	"\x13CurrencyRateService\x12N\n" +
	"\aGetRate\x12 .currency_rate.v1.GetRateRequest\x1a!.currency_rate.v1.GetRateResponse\x12Q\n" +
	"\bGetRates\x12!.currency_rate.v1.GetRatesRequest\x1a\".currency_rate.v1.GetRatesResponse\x12o\n" +
	"\x12ListSupportedPairs\x12+.currency_rate.v1.ListSupportedPairsRequest\x1a,.currency_rate.v1.ListSupportedPairsResponseB7Z5github.com/DigitLock/expense-tracker/internal/grpc/pbb\x06proto3"

var (
	file_currency_rate_proto_rawDescOnce sync.Once
	file_currency_rate_proto_rawDescData []byte
)

func file_currency_rate_proto_rawDescGZIP() []byte {
	file_currency_rate_proto_rawDescOnce.Do(func() {
		file_currency_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_rate_proto_rawDesc), len(file_currency_rate_proto_rawDesc)))
	})
	return file_currency_rate_proto_rawDescData
}

var file_currency_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_currency_rate_proto_goTypes = []any{
	(*Rate)(nil),                       // 0: currency_rate.v1.Rate
	(*CurrencyPair)(nil),               // 1: currency_rate.v1.CurrencyPair
	(*GetRateRequest)(nil),             // 2: currency_rate.v1.GetRateRequest
	(*GetRateResponse)(nil),            // 3: currency_rate.v1.GetRateResponse
	(*GetRatesRequest)(nil),            // 4: currency_rate.v1.GetRatesRequest
	(*GetRatesResponse)(nil),           // 5: currency_rate.v1.GetRatesResponse
	(*ListSupportedPairsRequest)(nil),  // 6: currency_rate.v1.ListSupportedPairsRequest
	(*ListSupportedPairsResponse)(nil), // 7: currency_rate.v1.ListSupportedPairsResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_currency_rate_proto_depIdxs = []int32{
	8, // 0: currency_rate.v1.Rate.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: currency_rate.v1.GetRateResponse.rate:type_name -> currency_rate.v1.Rate
	0, // 2: currency_rate.v1.GetRatesResponse.rates:type_name -> currency_rate.v1.Rate
	1, // 3: currency_rate.v1.ListSupportedPairsResponse.pairs:type_name -> currency_rate.v1.CurrencyPair
	2, // 4: currency_rate.v1.CurrencyRateService.GetRate:input_type -> currency_rate.v1.GetRateRequest
	4, // 5: currency_rate.v1.CurrencyRateService.GetRates:input_type -> currency_rate.v1.GetRatesRequest
	6, // 6: currency_rate.v1.CurrencyRateService.ListSupportedPairs:input_type -> currency_rate.v1.ListSupportedPairsRequest
	3, // 7: currency_rate.v1.CurrencyRateService.GetRate:output_type -> currency_rate.v1.GetRateResponse
	5, // 8: currency_rate.v1.CurrencyRateService.GetRates:output_type -> currency_rate.v1.GetRatesResponse
	7, // 9: currency_rate.v1.CurrencyRateService.ListSupportedPairs:output_type -> currency_rate.v1.ListSupportedPairsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_currency_rate_proto_init() }
func file_currency_rate_proto_init() {
	if File_currency_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_rate_proto_rawDesc), len(file_currency_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_rate_proto_goTypes,
		DependencyIndexes: file_currency_rate_proto_depIdxs,
		MessageInfos:      file_currency_rate_proto_msgTypes,
	}.Build()
	File_currency_rate_proto = out.File
	file_currency_rate_proto_goTypes = nil
	file_currency_rate_proto_depIdxs = nil
}
