// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: currency_rate.proto

// Vendored from currency-rate-service (github.com/DigitLock/currency-rate-service),
// proto/currency_rate/v1/service.proto. Contract is owned by that service; this is a
// client-side copy for ET's gRPC client. Keep the proto package as currency_rate.v1
// so the service full name matches the CRS server. Only go_package is repointed to
// ET's pb output. Re-sync on CRS contract changes (see docs/discovery/v0.3.0-st1-discovery.md).

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyRateService_GetRate_FullMethodName            = "/currency_rate.v1.CurrencyRateService/GetRate"
	CurrencyRateService_GetRates_FullMethodName           = "/currency_rate.v1.CurrencyRateService/GetRates"
	CurrencyRateService_ListSupportedPairs_FullMethodName = "/currency_rate.v1.CurrencyRateService/ListSupportedPairs"
)

// CurrencyRateServiceClient is the client API for CurrencyRateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyRateServiceClient interface {
	GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*GetRateResponse, error)
	GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error)
	ListSupportedPairs(ctx context.Context, in *ListSupportedPairsRequest, opts ...grpc.CallOption) (*ListSupportedPairsResponse, error)
}

type currencyRateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyRateServiceClient(cc grpc.ClientConnInterface) CurrencyRateServiceClient {
	return &currencyRateServiceClient{cc}
}

func (c *currencyRateServiceClient) GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*GetRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRateResponse)
	err := c.cc.Invoke(ctx, CurrencyRateService_GetRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRateServiceClient) GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatesResponse)
	err := c.cc.Invoke(ctx, CurrencyRateService_GetRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRateServiceClient) ListSupportedPairs(ctx context.Context, in *ListSupportedPairsRequest, opts ...grpc.CallOption) (*ListSupportedPairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedPairsResponse)
	err := c.cc.Invoke(ctx, CurrencyRateService_ListSupportedPairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyRateServiceServer is the server API for CurrencyRateService service.
// All implementations must embed UnimplementedCurrencyRateServiceServer
// for forward compatibility.
type CurrencyRateServiceServer interface {
	GetRate(context.Context, *GetRateRequest) (*GetRateResponse, error)
	GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error)
	ListSupportedPairs(context.Context, *ListSupportedPairsRequest) (*ListSupportedPairsResponse, error)
	mustEmbedUnimplementedCurrencyRateServiceServer()
}

// UnimplementedCurrencyRateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyRateServiceServer struct{}

func (UnimplementedCurrencyRateServiceServer) GetRate(context.Context, *GetRateRequest) (*GetRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedCurrencyRateServiceServer) GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedCurrencyRateServiceServer) ListSupportedPairs(context.Context, *ListSupportedPairsRequest) (*ListSupportedPairsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupportedPairs not implemented")
}
func (UnimplementedCurrencyRateServiceServer) mustEmbedUnimplementedCurrencyRateServiceServer() {}
func (UnimplementedCurrencyRateServiceServer) testEmbeddedByValue()                             {}

// UnsafeCurrencyRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyRateServiceServer will
// result in compilation errors.
type UnsafeCurrencyRateServiceServer interface {
	mustEmbedUnimplementedCurrencyRateServiceServer()
}

func RegisterCurrencyRateServiceServer(s grpc.ServiceRegistrar, srv CurrencyRateServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrencyRateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyRateService_ServiceDesc, srv)
}

func _CurrencyRateService_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRateServiceServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRateService_GetRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRateServiceServer).GetRate(ctx, req.(*GetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRateService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRateServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRateService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRateServiceServer).GetRates(ctx, req.(*GetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRateService_ListSupportedPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportedPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRateServiceServer).ListSupportedPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRateService_ListSupportedPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRateServiceServer).ListSupportedPairs(ctx, req.(*ListSupportedPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyRateService_ServiceDesc is the grpc.ServiceDesc for CurrencyRateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyRateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency_rate.v1.CurrencyRateService",
	HandlerType: (*CurrencyRateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRate",
			Handler:    _CurrencyRateService_GetRate_Handler,
		},
		{
			MethodName: "GetRates",
			Handler:    _CurrencyRateService_GetRates_Handler,
		},
		{
			MethodName: "ListSupportedPairs",
			Handler:    _CurrencyRateService_ListSupportedPairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency_rate.proto",
}
