// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reports.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpendingByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Optional: YYYY-MM-DD, default: month start
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Optional: YYYY-MM-DD, default: today
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                    // Optional: default family base currency
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                            // Optional: "income" or "expense", default: "expense"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendingByCategoryRequest) Reset() {
	*x = SpendingByCategoryRequest{}
	mi := &file_reports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingByCategoryRequest) ProtoMessage() {}

func (x *SpendingByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingByCategoryRequest.ProtoReflect.Descriptor instead.
func (*SpendingByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{0}
}

func (x *SpendingByCategoryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SpendingByCategoryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *SpendingByCategoryRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SpendingByCategoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SpendingByCategoryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReportType        string                 `protobuf:"bytes,1,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Period            *Period                `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionType   string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Categories        []*CategorySpending    `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	TotalAmount       float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,7,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	GeneratedAt       string                 `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpendingByCategoryResponse) Reset() {
	*x = SpendingByCategoryResponse{}
	mi := &file_reports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingByCategoryResponse) ProtoMessage() {}

func (x *SpendingByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingByCategoryResponse.ProtoReflect.Descriptor instead.
func (*SpendingByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{1}
}

func (x *SpendingByCategoryResponse) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *SpendingByCategoryResponse) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *SpendingByCategoryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SpendingByCategoryResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *SpendingByCategoryResponse) GetCategories() []*CategorySpending {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SpendingByCategoryResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *SpendingByCategoryResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *SpendingByCategoryResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_reports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{2}
}

func (x *Period) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Period) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CategorySpending struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CategoryId            string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName          string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	TotalAmount           float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TransactionCount      int32                  `protobuf:"varint,4,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	Percentage            float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	AveragePerTransaction float64                `protobuf:"fixed64,6,opt,name=average_per_transaction,json=averagePerTransaction,proto3" json:"average_per_transaction,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CategorySpending) Reset() {
	*x = CategorySpending{}
	mi := &file_reports_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySpending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySpending) ProtoMessage() {}

func (x *CategorySpending) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySpending.ProtoReflect.Descriptor instead.
func (*CategorySpending) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{3}
}

func (x *CategorySpending) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategorySpending) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategorySpending) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CategorySpending) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *CategorySpending) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *CategorySpending) GetAveragePerTransaction() float64 {
	if x != nil {
		return x.AveragePerTransaction
	}
	return 0
}

type MonthlySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`       // Optional: YYYY-MM, default: current month
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // Optional: default family base currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySummaryRequest) Reset() {
	*x = MonthlySummaryRequest{}
	mi := &file_reports_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySummaryRequest) ProtoMessage() {}

func (x *MonthlySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySummaryRequest.ProtoReflect.Descriptor instead.
func (*MonthlySummaryRequest) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlySummaryRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlySummaryRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type MonthlySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,3,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpenses float64                `protobuf:"fixed64,4,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetBalance    float64                `protobuf:"fixed64,5,opt,name=net_balance,json=netBalance,proto3" json:"net_balance,omitempty"`
	IncomeCount   int32                  `protobuf:"varint,6,opt,name=income_count,json=incomeCount,proto3" json:"income_count,omitempty"`
	ExpenseCount  int32                  `protobuf:"varint,7,opt,name=expense_count,json=expenseCount,proto3" json:"expense_count,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySummaryResponse) Reset() {
	*x = MonthlySummaryResponse{}
	mi := &file_reports_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySummaryResponse) ProtoMessage() {}

func (x *MonthlySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reports_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySummaryResponse.ProtoReflect.Descriptor instead.
func (*MonthlySummaryResponse) Descriptor() ([]byte, []int) {
	return file_reports_proto_rawDescGZIP(), []int{5}
}

func (x *MonthlySummaryResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlySummaryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MonthlySummaryResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *MonthlySummaryResponse) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *MonthlySummaryResponse) GetNetBalance() float64 {
	if x != nil {
		return x.NetBalance
	}
	return 0
}

func (x *MonthlySummaryResponse) GetIncomeCount() int32 {
	if x != nil {
		return x.IncomeCount
	}
	return 0
}

func (x *MonthlySummaryResponse) GetExpenseCount() int32 {
	if x != nil {
		return x.ExpenseCount
	}
	return 0
}

func (x *MonthlySummaryResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

var File_reports_proto protoreflect.FileDescriptor

const file_reports_proto_rawDesc = "" +
	"\n" +
	"\rreports.proto\x12\x12expense_tracker.v1\"\x85\x01\n" +
	"\x19SpendingByCategoryRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xf3\x02\n" +
	"\x1aSpendingByCategoryResponse\x12\x1f\n" +
	"\vreport_type\x18\x01 \x01(\tR\n" +
	"reportType\x122\n" +
	"\x06period\x18\x02 \x01(\v2\x1a.expense_tracker.v1.PeriodR\x06period\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12D\n" +
	"\n" +
	"categories\x18\x05 \x03(\v2$.expense_tracker.v1.CategorySpendingR\n" +
	"categories\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x12-\n" +
	"\x12total_transactions\x18\a \x01(\x05R\x11totalTransactions\x12!\n" +
	"\fgenerated_at\x18\b \x01(\tR\vgeneratedAt\"B\n" +
	"\x06Period\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"\x80\x02\n" +
	"\x10CategorySpending\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12+\n" +
	"\x11transaction_count\x18\x04 \x01(\x05R\x10transactionCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\x126\n" +
	"\x17average_per_transaction\x18\x06 \x01(\x01R\x15averagePerTransaction\"I\n" +
	"\x15MonthlySummaryRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xa0\x02\n" +
	"\x16MonthlySummaryResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12!\n" +
	"\ftotal_income\x18\x03 \x01(\x01R\vtotalIncome\x12%\n" +
	"\x0etotal_expenses\x18\x04 \x01(\x01R\rtotalExpenses\x12\x1f\n" +
	"\vnet_balance\x18\x05 \x01(\x01R\n" +
	"netBalance\x12!\n" +
	"\fincome_count\x18\x06 \x01(\x05R\vincomeCount\x12#\n" +
	"\rexpense_count\x18\a \x01(\x05R\fexpenseCount\x12!\n" +
	"\fgenerated_at\x18\b \x01(\tR\vgeneratedAt2\xf3\x01\n" +
	"\rReportService\x12v\n" +
	"\x15GetSpendingByCategory\x12-.expense_tracker.v1.SpendingByCategoryRequest\x1a..expense_tracker.v1.SpendingByCategoryResponse\x12j\n" +
	"\x11GetMonthlySummary\x12).expense_tracker.v1.MonthlySummaryRequest\x1a*.expense_tracker.v1.MonthlySummaryResponseB7Z5github.com/DigitLock/expense-tracker/internal/grpc/pbb\x06proto3"

var (
	file_reports_proto_rawDescOnce sync.Once
	file_reports_proto_rawDescData []byte
)

func file_reports_proto_rawDescGZIP() []byte {
	file_reports_proto_rawDescOnce.Do(func() {
		file_reports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reports_proto_rawDesc), len(file_reports_proto_rawDesc)))
	})
	return file_reports_proto_rawDescData
}

var file_reports_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reports_proto_goTypes = []any{
	(*SpendingByCategoryRequest)(nil),  // 0: expense_tracker.v1.SpendingByCategoryRequest
	(*SpendingByCategoryResponse)(nil), // 1: expense_tracker.v1.SpendingByCategoryResponse
	(*Period)(nil),                     // 2: expense_tracker.v1.Period
	(*CategorySpending)(nil),           // 3: expense_tracker.v1.CategorySpending
	(*MonthlySummaryRequest)(nil),      // 4: expense_tracker.v1.MonthlySummaryRequest
	(*MonthlySummaryResponse)(nil),     // 5: expense_tracker.v1.MonthlySummaryResponse
}
var file_reports_proto_depIdxs = []int32{
	2, // 0: expense_tracker.v1.SpendingByCategoryResponse.period:type_name -> expense_tracker.v1.Period
	3, // 1: expense_tracker.v1.SpendingByCategoryResponse.categories:type_name -> expense_tracker.v1.CategorySpending
	0, // 2: expense_tracker.v1.ReportService.GetSpendingByCategory:input_type -> expense_tracker.v1.SpendingByCategoryRequest
	4, // 3: expense_tracker.v1.ReportService.GetMonthlySummary:input_type -> expense_tracker.v1.MonthlySummaryRequest
	1, // 4: expense_tracker.v1.ReportService.GetSpendingByCategory:output_type -> expense_tracker.v1.SpendingByCategoryResponse
	5, // 5: expense_tracker.v1.ReportService.GetMonthlySummary:output_type -> expense_tracker.v1.MonthlySummaryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reports_proto_init() }
func file_reports_proto_init() {
	if File_reports_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reports_proto_rawDesc), len(file_reports_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reports_proto_goTypes,
		DependencyIndexes: file_reports_proto_depIdxs,
		MessageInfos:      file_reports_proto_msgTypes,
	}.Build()
	File_reports_proto = out.File
	file_reports_proto_goTypes = nil
	file_reports_proto_depIdxs = nil
}
