// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, family_id, name, type, currency, initial_balance, current_balance
) VALUES (
             $1, $2, $3, $4, $5, $6, $6
         )
RETURNING id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active
`

type CreateAccountParams struct {
	ID             uuid.UUID       `json:"id"`
	FamilyID       uuid.UUID       `json:"family_id"`
	Name           string          `json:"name"`
	Type           string          `json:"type"`
	Currency       string          `json:"currency"`
	InitialBalance decimal.Decimal `json:"initial_balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.InitialBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active FROM accounts
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT current_balance, currency FROM accounts
WHERE id = $1 AND is_active = true
`

type GetAccountBalanceRow struct {
	CurrentBalance decimal.Decimal `json:"current_balance"`
	Currency       string          `json:"currency"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (GetAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, id)
	var i GetAccountBalanceRow
	err := row.Scan(&i.CurrentBalance, &i.Currency)
	return i, err
}

const getAccountIncludingInactive = `-- name: GetAccountIncludingInactive :one
SELECT id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountIncludingInactive(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountIncludingInactive, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getTotalBalanceByFamily = `-- name: GetTotalBalanceByFamily :one
SELECT
    COALESCE(SUM(current_balance), 0)::numeric as total_balance,
    COUNT(*) as account_count
FROM accounts
WHERE family_id = $1 AND is_active = true
`

type GetTotalBalanceByFamilyRow struct {
	TotalBalance decimal.Decimal `json:"total_balance"`
	AccountCount int64           `json:"account_count"`
}

func (q *Queries) GetTotalBalanceByFamily(ctx context.Context, familyID uuid.UUID) (GetTotalBalanceByFamilyRow, error) {
	row := q.db.QueryRow(ctx, getTotalBalanceByFamily, familyID)
	var i GetTotalBalanceByFamilyRow
	err := row.Scan(&i.TotalBalance, &i.AccountCount)
	return i, err
}

const listAccountsByFamily = `-- name: ListAccountsByFamily :many
SELECT id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active FROM accounts
WHERE family_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListAccountsByFamily(ctx context.Context, familyID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByType = `-- name: ListAccountsByType :many
SELECT id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active FROM accounts
WHERE family_id = $1 AND type = $2 AND is_active = true
ORDER BY name
`

type ListAccountsByTypeParams struct {
	FamilyID uuid.UUID `json:"family_id"`
	Type     string    `json:"type"`
}

func (q *Queries) ListAccountsByType(ctx context.Context, arg ListAccountsByTypeParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByType, arg.FamilyID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccountsByFamily = `-- name: ListAllAccountsByFamily :many
SELECT id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active FROM accounts
WHERE family_id = $1
ORDER BY name
`

func (q *Queries) ListAllAccountsByFamily(ctx context.Context, familyID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAllAccountsByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = $2,
    is_active = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, family_id, name, type, currency, initial_balance, current_balance, description, created_at, updated_at, is_active
`

type UpdateAccountParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Name, arg.IsActive)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
