// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    id, family_id, name, type, parent_id
) VALUES (
             $1, $2, $3, $4, $5
         )
RETURNING id, family_id, name, type, parent_id, description, created_at, updated_at, is_active
`

type CreateCategoryParams struct {
	ID       uuid.UUID   `json:"id"`
	FamilyID uuid.UUID   `json:"family_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.Type,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getCategoryIncludingInactive = `-- name: GetCategoryIncludingInactive :one
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryIncludingInactive(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryIncludingInactive, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listAllCategoriesByFamily = `-- name: ListAllCategoriesByFamily :many
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE family_id = $1
ORDER BY type, name
`

func (q *Queries) ListAllCategoriesByFamily(ctx context.Context, familyID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listAllCategoriesByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByFamily = `-- name: ListCategoriesByFamily :many
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE family_id = $1 AND is_active = true
ORDER BY type, name
`

func (q *Queries) ListCategoriesByFamily(ctx context.Context, familyID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByType = `-- name: ListCategoriesByType :many
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE family_id = $1 AND type = $2 AND is_active = true
ORDER BY name
`

type ListCategoriesByTypeParams struct {
	FamilyID uuid.UUID `json:"family_id"`
	Type     string    `json:"type"`
}

func (q *Queries) ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByType, arg.FamilyID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE parent_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, family_id, name, type, parent_id, description, created_at, updated_at, is_active FROM categories
WHERE family_id = $1 AND parent_id IS NULL AND is_active = true
ORDER BY type, name
`

func (q *Queries) ListRootCategories(ctx context.Context, familyID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listRootCategories, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $2,
    parent_id = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, family_id, name, type, parent_id, description, created_at, updated_at, is_active
`

type UpdateCategoryParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
