// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: families.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (
    id, name, base_currency
) VALUES (
             $1, $2, $3
         )
RETURNING id, name, base_currency, created_at, updated_at, is_active
`

type CreateFamilyParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.ID, arg.Name, arg.BaseCurrency)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteFamily = `-- name: DeleteFamily :exec
UPDATE families
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteFamily(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFamily, id)
	return err
}

const getFamily = `-- name: GetFamily :one
SELECT id, name, base_currency, created_at, updated_at, is_active FROM families
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetFamily(ctx context.Context, id uuid.UUID) (Family, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getFamilyByName = `-- name: GetFamilyByName :one
SELECT id, name, base_currency, created_at, updated_at, is_active FROM families
WHERE name = $1 AND is_active = true
`

func (q *Queries) GetFamilyByName(ctx context.Context, name string) (Family, error) {
	row := q.db.QueryRow(ctx, getFamilyByName, name)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listFamilies = `-- name: ListFamilies :many
SELECT id, name, base_currency, created_at, updated_at, is_active FROM families
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListFamilies(ctx context.Context) ([]Family, error) {
	rows, err := q.db.Query(ctx, listFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Family{}
	for rows.Next() {
		var i Family
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFamily = `-- name: UpdateFamily :one
UPDATE families
SET
    name = $2,
    base_currency = $3,
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, name, base_currency, created_at, updated_at, is_active
`

type UpdateFamilyParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
}

func (q *Queries) UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, updateFamily, arg.ID, arg.Name, arg.BaseCurrency)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
