// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Financial accounts for cash and bank accounts. Each account belongs to a family and has a type and currency.
type Account struct {
	// UUID primary key. Generated automatically.
	ID uuid.UUID `json:"id"`
	// Foreign key to families. ON DELETE CASCADE.
	FamilyID uuid.UUID `json:"family_id"`
	// User-defined account name. Examples: "My Wallet", "Salary Card", "Vacation Savings"
	Name string `json:"name"`
	// Account type: cash (physical cash), checking (current/debit account), savings (savings account/deposit)
	Type string `json:"type"`
	// Account currency. MVP: RSD or EUR only. Post-MVP: any currency.
	Currency string `json:"currency"`
	// Starting balance when account was created. Does NOT change after creation. Used for balance calculations.
	InitialBalance decimal.Decimal `json:"initial_balance"`
	// Current account balance. AUTOMATICALLY calculated by trigger based on transactions. Formula: initial_balance + SUM(income) - SUM(expense). DO NOT update manually!
	CurrentBalance decimal.Decimal `json:"current_balance"`
	// Optional description/notes about the account
	Description pgtype.Text `json:"description"`
	// Timestamp when account was created. Set automatically.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp of last update. Updated automatically by trigger.
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete flag. true = active account, false = closed account (data preserved for history)
	IsActive bool `json:"is_active"`
}

// Complete audit trail of all data changes. Automatically populated by triggers.
type AuditLog struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"family_id"`
	// User who made the change. Retrieved from session variable app.current_user_id. NULL for system changes or if user was deleted.
	UserID pgtype.UUID `json:"user_id"`
	// Name of table that was changed: users, accounts, categories, transactions
	TableName string `json:"table_name"`
	// ID of the record that was changed
	RecordID uuid.UUID `json:"record_id"`
	// Type of operation: INSERT, UPDATE, DELETE
	Action string `json:"action"`
	// JSONB snapshot of record BEFORE change. NULL for INSERT.
	BeforeData []byte `json:"before_data"`
	// JSONB snapshot of record AFTER change. NULL for DELETE.
	AfterData []byte    `json:"after_data"`
	CreatedAt time.Time `json:"created_at"`
}

// Income and expense categories for transaction classification. Supports hierarchical structure (parent-child relationships).
type Category struct {
	// UUID primary key. Generated automatically.
	ID uuid.UUID `json:"id"`
	// Foreign key to families. ON DELETE CASCADE.
	FamilyID uuid.UUID `json:"family_id"`
	// Category name. Examples: "Food", "Groceries", "Salary". Must be unique per family and type.
	Name string `json:"name"`
	// Category type: income (for income transactions) or expense (for expense transactions)
	Type string `json:"type"`
	// Parent category ID for hierarchical structure. NULL = top-level category. Example: "Food" (parent) -> "Groceries" (child with parent_id = Food.id)
	ParentID pgtype.UUID `json:"parent_id"`
	// Optional category description
	Description pgtype.Text `json:"description"`
	// Timestamp when category was created. Set automatically.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp of last update. Updated automatically by trigger.
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete flag. true = active category, false = deleted category (transactions preserved)
	IsActive bool `json:"is_active"`
}

// Historical currency exchange rates for multi-currency support. Updated daily via external API.
type ExchangeRate struct {
	ID uuid.UUID `json:"id"`
	// Source currency code. MVP: RSD or EUR only.
	FromCurrency string `json:"from_currency"`
	// Target currency code. MVP: RSD or EUR only.
	ToCurrency string `json:"to_currency"`
	// Exchange rate: 1 from_currency = rate * to_currency. Example: 1 EUR = 117.50 RSD. DECIMAL(15,6) for high precision.
	Rate decimal.Decimal `json:"rate"`
	// Date for which this rate is valid. One rate per currency pair per day.
	Date pgtype.Date `json:"date"`
	// Source of exchange rate. Examples: "exchangerate-api.com", "fixer.io", "manual", "central-bank-serbia"
	Source string `json:"source"`
	// Timestamp when rate was inserted into database. Not the same as rate.date!
	CreatedAt time.Time `json:"created_at"`
}

// Family/household entities for financial data isolation. Root table for multi-tenancy.
type Family struct {
	// UUID primary key. Generated automatically. Used as family_id in all related tables.
	ID uuid.UUID `json:"id"`
	// Family display name. Example: "Kudinov Family", "Test Family"
	Name string `json:"name"`
	// Base currency for financial reporting. MVP: Only RSD supported. Post-MVP: User-configurable (EUR, USD, etc.)
	BaseCurrency string `json:"base_currency"`
	// Timestamp when family was created. Set automatically.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp of last update. Updated automatically by trigger.
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete flag. true = active family, false = deleted family (data preserved for history)
	IsActive bool `json:"is_active"`
}

// Core financial transactions (income and expenses). Automatic balance calculation via trigger.
type Transaction struct {
	ID         uuid.UUID `json:"id"`
	FamilyID   uuid.UUID `json:"family_id"`
	AccountID  uuid.UUID `json:"account_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Type       string    `json:"type"`
	// Transaction amount in original currency. Always positive (type determines income/expense).
	Amount decimal.Decimal `json:"amount"`
	// Original transaction currency (RSD or EUR in MVP)
	Currency string `json:"currency"`
	// Amount converted to base currency (RSD) using exchange rate at transaction date. Used for reports and balance calculations.
	AmountBase  decimal.Decimal `json:"amount_base"`
	Description pgtype.Text     `json:"description"`
	// Date when transaction occurred (not when it was recorded). Cannot be in future.
	TransactionDate pgtype.Date `json:"transaction_date"`
	// User who created this transaction. For audit trail.
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsActive  bool      `json:"is_active"`
}

// User accounts for family members with authentication credentials
type User struct {
	// UUID primary key. Generated automatically.
	ID uuid.UUID `json:"id"`
	// Foreign key to families table. Every user belongs to one family. ON DELETE CASCADE.
	FamilyID uuid.UUID `json:"family_id"`
	// User email address. Used for login. Must be globally unique. Format validated by constraint.
	Email string `json:"email"`
	// Bcrypt hashed password (12 rounds minimum recommended). NEVER store plain text passwords!
	PasswordHash string `json:"password_hash"`
	// Display name for user. Example: "Igor Kudinov", "Жена"
	Name string `json:"name"`
	// Timestamp when user account was created. Set automatically.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp of last profile update. Updated automatically by trigger.
	UpdatedAt time.Time `json:"updated_at"`
	// Timestamp of last successful login. Updated by application on login. NULL if never logged in.
	LastLoginAt pgtype.Timestamp `json:"last_login_at"`
	// Soft delete flag. true = active user, false = deleted/blocked user (data preserved for audit)
	IsActive bool `json:"is_active"`
}

// Convenient view of audit log with joined family and user names
type VRecentAuditLog struct {
	ID         uuid.UUID   `json:"id"`
	FamilyName pgtype.Text `json:"family_name"`
	UserName   pgtype.Text `json:"user_name"`
	UserEmail  pgtype.Text `json:"user_email"`
	TableName  string      `json:"table_name"`
	Action     string      `json:"action"`
	RecordID   uuid.UUID   `json:"record_id"`
	CreatedAt  time.Time   `json:"created_at"`
	BeforeData []byte      `json:"before_data"`
	AfterData  []byte      `json:"after_data"`
}
