// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTransactionsByFamily(ctx context.Context, familyID uuid.UUID) (int64, error)
	CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteFamily(ctx context.Context, id uuid.UUID) error
	DeleteTransaction(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountBalance(ctx context.Context, id uuid.UUID) (GetAccountBalanceRow, error)
	GetAccountIncludingInactive(ctx context.Context, id uuid.UUID) (Account, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryIncludingInactive(ctx context.Context, id uuid.UUID) (Category, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error)
	GetFamily(ctx context.Context, id uuid.UUID) (Family, error)
	GetFamilyByName(ctx context.Context, name string) (Family, error)
	GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error)
	GetTotalBalanceByFamily(ctx context.Context, familyID uuid.UUID) (GetTotalBalanceByFamilyRow, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionIncludingInactive(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsSummaryByCategory(ctx context.Context, arg GetTransactionsSummaryByCategoryParams) ([]GetTransactionsSummaryByCategoryRow, error)
	GetTransactionsSummaryByType(ctx context.Context, arg GetTransactionsSummaryByTypeParams) ([]GetTransactionsSummaryByTypeRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAccountsByFamily(ctx context.Context, familyID uuid.UUID) ([]Account, error)
	ListAccountsByType(ctx context.Context, arg ListAccountsByTypeParams) ([]Account, error)
	ListAllAccountsByFamily(ctx context.Context, familyID uuid.UUID) ([]Account, error)
	ListAllCategoriesByFamily(ctx context.Context, familyID uuid.UUID) ([]Category, error)
	ListCategoriesByFamily(ctx context.Context, familyID uuid.UUID) ([]Category, error)
	ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error)
	ListChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	ListExchangeRatesByDate(ctx context.Context, date pgtype.Date) ([]ExchangeRate, error)
	ListExchangeRatesHistory(ctx context.Context, arg ListExchangeRatesHistoryParams) ([]ExchangeRate, error)
	ListFamilies(ctx context.Context) ([]Family, error)
	ListRootCategories(ctx context.Context, familyID uuid.UUID) ([]Category, error)
	ListTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]Transaction, error)
	ListTransactionsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Transaction, error)
	ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error)
	ListTransactionsByFamily(ctx context.Context, familyID uuid.UUID) ([]Transaction, error)
	ListTransactionsFiltered(ctx context.Context, arg ListTransactionsFilteredParams) ([]Transaction, error)
	ListTransactionsPaginated(ctx context.Context, arg ListTransactionsPaginatedParams) ([]Transaction, error)
	ListUsersByFamily(ctx context.Context, familyID uuid.UUID) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error)
}

var _ Querier = (*Queries)(nil)
