// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, family_id, account_id, category_id, type,
    amount, currency, amount_base, description, transaction_date
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
         )
RETURNING id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active
`

type CreateTransactionParams struct {
	ID              uuid.UUID       `json:"id"`
	FamilyID        uuid.UUID       `json:"family_id"`
	AccountID       uuid.UUID       `json:"account_id"`
	CategoryID      uuid.UUID       `json:"category_id"`
	Type            string          `json:"type"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	AmountBase      decimal.Decimal `json:"amount_base"`
	Description     pgtype.Text     `json:"description"`
	TransactionDate pgtype.Date     `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.FamilyID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.AmountBase,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
UPDATE transactions
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getTransactionsSummaryByCategory = `-- name: GetTransactionsSummaryByCategory :many
SELECT
    category_id,
    COUNT(*) as count,
    COALESCE(SUM(amount_base), 0)::numeric as total
FROM transactions
WHERE family_id = $1
  AND type = $2
  AND transaction_date >= $3
  AND transaction_date <= $4
  AND is_active = true
GROUP BY category_id
ORDER BY total DESC
`

type GetTransactionsSummaryByCategoryParams struct {
	FamilyID          uuid.UUID   `json:"family_id"`
	Type              string      `json:"type"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetTransactionsSummaryByCategoryRow struct {
	CategoryID uuid.UUID       `json:"category_id"`
	Count      int64           `json:"count"`
	Total      decimal.Decimal `json:"total"`
}

func (q *Queries) GetTransactionsSummaryByCategory(ctx context.Context, arg GetTransactionsSummaryByCategoryParams) ([]GetTransactionsSummaryByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsSummaryByCategory,
		arg.FamilyID,
		arg.Type,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsSummaryByCategoryRow{}
	for rows.Next() {
		var i GetTransactionsSummaryByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Count, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsSummaryByType = `-- name: GetTransactionsSummaryByType :many
SELECT
    type,
    COUNT(*) as count,
    COALESCE(SUM(amount_base), 0)::numeric as total
FROM transactions
WHERE family_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND is_active = true
GROUP BY type
`

type GetTransactionsSummaryByTypeParams struct {
	FamilyID          uuid.UUID   `json:"family_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetTransactionsSummaryByTypeRow struct {
	Type  string          `json:"type"`
	Count int64           `json:"count"`
	Total decimal.Decimal `json:"total"`
}

func (q *Queries) GetTransactionsSummaryByType(ctx context.Context, arg GetTransactionsSummaryByTypeParams) ([]GetTransactionsSummaryByTypeRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsSummaryByType, arg.FamilyID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsSummaryByTypeRow{}
	for rows.Next() {
		var i GetTransactionsSummaryByTypeRow
		if err := rows.Scan(&i.Type, &i.Count, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE account_id = $1 AND is_active = true
ORDER BY transaction_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCategory = `-- name: ListTransactionsByCategory :many
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE category_id = $1 AND is_active = true
ORDER BY transaction_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE family_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND is_active = true
ORDER BY transaction_date DESC, created_at DESC
`

type ListTransactionsByDateRangeParams struct {
	FamilyID          uuid.UUID   `json:"family_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange, arg.FamilyID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByFamily = `-- name: ListTransactionsByFamily :many
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE family_id = $1 AND is_active = true
ORDER BY transaction_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByFamily(ctx context.Context, familyID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsPaginated = `-- name: ListTransactionsPaginated :many
SELECT id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active FROM transactions
WHERE family_id = $1 AND is_active = true
ORDER BY transaction_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsPaginatedParams struct {
	FamilyID uuid.UUID `json:"family_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTransactionsPaginated(ctx context.Context, arg ListTransactionsPaginatedParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsPaginated, arg.FamilyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    category_id = $2,
    amount = $3,
    currency = $4,
    amount_base = $5,
    description = $6,
    transaction_date = $7,
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, family_id, account_id, category_id, type, amount, currency, amount_base, description, transaction_date, created_by, created_at, updated_at, is_active
`

type UpdateTransactionParams struct {
	ID              uuid.UUID       `json:"id"`
	CategoryID      uuid.UUID       `json:"category_id"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	AmountBase      decimal.Decimal `json:"amount_base"`
	Description     pgtype.Text     `json:"description"`
	TransactionDate pgtype.Date     `json:"transaction_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.AmountBase,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
